//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication111.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agencija()
        {
            this.kucas = new HashSet<kuca>();
            this.stans = new HashSet<stan>();
        }
    
        public int ID_agencija { get; set; }
        public string ime_agencije { get; set; }
        public string kontakt_telefon { get; set; }
        public string e_mail { get; set; }
        public string web_sajt { get; set; }
        public string adresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kuca> kucas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stan> stans { get; set; }
    }
}
