//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication111.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public System.Guid ID { get; set; }
        public string Poruka1 { get; set; }
        public string Ime { get; set; }
        public string Email { get; set; }
    }
}
