//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication111.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stan
    {
        public int ID_stan { get; set; }
        public Nullable<int> broj_stana { get; set; }
        public string vlasnik_stana { get; set; }
        public Nullable<bool> kupatilo { get; set; }
        public Nullable<int> kvadratura { get; set; }
        public Nullable<int> broj_soba { get; set; }
        public Nullable<bool> balkon { get; set; }
        public int ID_zgrada { get; set; }
        public int ID_agencija { get; set; }
    
        public virtual agencija agencija { get; set; }
        public virtual zgrada zgrada { get; set; }
    }
}
